
default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: root
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: ecommerce_api_test

development:
  <<: *default
  database: ecommerce_api_development

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV["ECOMMERCE_API_DATABASE_PASSWORD"] %>
